### ISSUE TITLE
Question how do I install a plug-in with this

### ISSUE THREAD

**Issue by CuriousCoder1232** [darverdevs/PluginInstaller#4]
So do I need the plug-in jar in replit and do install plug-in name  or it searches for plugins

**Comment by sleepy1235** [comment]
doesnt work. 

>install LoginSecurity-3.2.0-Bukkit.jar
07:18:48 [INFO] /install <plugin>
>/install LoginSecurity-3.2.0-Bukkit.jar
07:18:58 [INFO] Unknown command. Type "help" for help.
